monotonicity: prevent race condition
ethereum-optimism/go-ethereum pull request #305
Opened 2021-04-08 00:30 UTC by tynes

## Description
Adds a fix for the race condition that would allow for a monotonicity violation. This is important to maintain liveliness while keeping the verifier and sequencer state in sync

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](./CONTRIBUTING.md) and am following those guidelines in this pull request.

2021-04-08 17:10 UTC, gakonst commented on miner/worker.go
> +		log.Error("Monotonicity violation", "index", num)
Should we be `panic`ing instead?

2021-04-09 03:49 UTC, karlfloersch approved these changes
LGTM

2021-04-09 03:54 UTC, karlfloersch requested changes
Update monotonicity error handling pls

2021-04-09 04:24 UTC, karlfloersch commented on miner/worker.go
> +			tx.SetL1Timestamp(parent.Time())
Set timestamp and block number?

2021-04-09 04:51 UTC, merged

2021-04-09 04:51 UTC, karlfloersch approved these changes